### ISSUE TITLE
Autogrow on Template

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/VITAC-NIDays#1]
The given when then template should have autogrow disabled because it is awful.

**Comment by joerghampel** [comment]
what exactly do you want me to change??

**Comment by JamesMc86** [comment]
In the given when then.vi in the templates folder - the sequence structure should not have autogrow

**Comment by joerghampel** [comment]
I'm on it

**Comment by JamesMc86** [comment]
Merged PR #2
